# n=500

```{r setup, include=FALSE}
library(gtools)
library(xtable)
library(ggplot2)
library(plotly)#used for plotting
library(kableExtra)
library(reshape2)
library(survey)
library(knitr)

pathy="C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Code/ComputerExperiments/Simulation II/"
source(paste0(pathy,"Common_Functions.R"))

formula1="A1~-1+X1"
formula2="A2~-1+X2+A1"
weight_estimate=TRUE
normalized=TRUE
bayes=FALSE
covtype=3
```


```{r, echo=FALSE}
set.seed(1)
n=500
formula1="A1~-1+X1"
formula2="A2~-1+X2+A1"
expit=function(x) 1 / (1 + exp(-x))
fact=1.5
X1=rnorm(n,0,1*fact)
A1_Opt=(X1-1.0*fact)>0+0
A1 = rbinom(n, 1, expit(-1/fact*X1))
X2=1*fact*A1+rnorm(n,0,1*fact)
A2_Opt=(X2-.5*fact)>0
A2=rbinom(n, 1, expit(-1/fact*X2+1/fact*A1))
Y=0.2*(X1-(X1+1.5*fact)*(X1+1*fact)*(X1+0.2*fact)*(X1-1.2*fact)*(X1-.5*fact)*(A1_Opt-A1)-(X2+1.4*fact)*(X2+1.1*fact)*(X2+0.2*fact)*(X2-1.4*fact)*(X2-0.9*fact)*(A2_Opt-A2))+rnorm(n,0,0.3)
richi=t(rdirichlet(1, rep(1,n)))


Datai=data.frame(X1,A1_Opt,A1,X2,A2_Opt,A2,Y)
proba=compute_probas(formula1=formula1,
                     formula2=formula2,
                     Dati=Datai,bayes=bayes,dirichi=richi)


sequence1=seq(-1.5,1.2,.05)*fact #this only comes in at the end
sequence2=seq(-1.5,1.2,.05)*fact

theta=as.matrix(expand.grid(sequence1,sequence2))
design1=theta[,1]
design2=theta[,2]
y=apply(theta,1,FUN=checki_compliant2d,Dati=Datai,weight_estimate=weight_estimate, proba=proba, normalized=normalized,bayes=bayes,dirichi=richi)


data_grid2=data.frame(theta1=theta[,1],
                      theta2=theta[,2],
                      value=y)
plot_matrix2 <- t(acast(data_grid2, theta1~ theta2, value.var="value"))

plot_ly(
  x = as.numeric(colnames(plot_matrix2)),
  y = as.numeric(rownames(plot_matrix2)),
  z = plot_matrix2) %>%
  add_surface()%>%
  layout(title="Value of Regime for Varying Cutoffs \n IPW",
         scene=list(xaxis = list(title="Psi_1"),
                    yaxis = list(title="Psi_2"),
                    zaxis =  list(title="Y")))
## Contour Plot
fig=plot_ly(x=~theta[,1],
            y=~theta[,2],
            z=~y, type="contour",
            colorscale="Greys",line=list(color="black"), contours = list(showlabels = TRUE))
fig%>%colorbar(title = "Value")%>%
  layout(xaxis = list(title = TeX("\\psi_1")),
         yaxis = list(title = TeX("\\psi_2"))) %>% 
         config(mathjax = 'cdn')
```

