## Matern 5/2 (n=500)

```{r setup, include=FALSE}
library(gtools)
library(xtable)
library(ggplot2)
library(plotly)#used for plotting
library(kableExtra)
library(reshape2)
library(survey)
library(knitr)

pathy="C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Code/ComputerExperiments/Simulation II/"
source(paste0(pathy,"Common_Functions.R"))

formula1="A1~-1+X1"
formula2="A2~-1+X2+A1"
# weight_estimate=TRUE
normalized=TRUE
bayes=FALSE
covtype=3
```


### Estimated Value Function
```{r, echo=FALSE}
set.seed(1)
n=500
formula1="A1~-1+X1"
formula2="A2~-1+X2+A1"
expit=function(x) 1 / (1 + exp(-x))
fact=1.5
X1=rnorm(n,0,1*fact)
A1_Opt=(X1-1.0*fact)>0+0
A1 = rbinom(n, 1, expit(-1/fact*X1))
X2=1*fact*A1+rnorm(n,0,1*fact)
A2_Opt=(X2-.5*fact)>0
A2=rbinom(n, 1, expit(-1/fact*X2+1/fact*A1))
Y=0.2*(X1-(X1+1.5*fact)*(X1+1*fact)*(X1+0.2*fact)*(X1-1.2*fact)*(X1-.5*fact)*(A1_Opt-A1)-(X2+1.4*fact)*(X2+1.1*fact)*(X2+0.2*fact)*(X2-1.4*fact)*(X2-0.9*fact)*(A2_Opt-A2))+rnorm(n,0,0.3)
richi=t(rdirichlet(1, rep(1,n)))


Datai=data.frame(X1,A1_Opt,A1,X2,A2_Opt,A2,Y)
proba=compute_probas(formula1=formula1,
                     formula2=formula2,
                     Dati=Datai,bayes=bayes,dirichi=richi)


sequence1=seq(-1.5,1.2,.05)*fact #this only comes in at the end
sequence2=seq(-1.5,1.2,.05)*fact

theta=as.matrix(expand.grid(sequence1,sequence2))
design1=theta[,1]
design2=theta[,2]
y=apply(theta,1,FUN=checki_compliant2d,Dati=Datai, proba=proba, normalized=normalized,bayes=bayes,dirichi=richi)


data_grid2=data.frame(theta1=theta[,1],
                      theta2=theta[,2],
                      value=y)
plot_matrix2 <- t(acast(data_grid2, theta1~ theta2, value.var="value"))

plot_ly(
  x = as.numeric(colnames(plot_matrix2)),
  y = as.numeric(rownames(plot_matrix2)),
  z = plot_matrix2) %>%
  add_surface()%>%
  layout(title="Value of Regime for Varying Cutoffs \n IPW",
         scene=list(xaxis = list(title="Psi_1"),
                    yaxis = list(title="Psi_2"),
                    zaxis =  list(title="Y")))
# # Contour Plot
# fig=plot_ly(x=~theta[,1],
#             y=~theta[,2],
#             z=~y, type="contour",
#             colorscale="Greys",line=list(color="black"), contours = list(showlabels = TRUE))
# fig%>%colorbar(title = "Value")%>%
#   layout(xaxis = list(title = TeX("\\psi_1")),
#          yaxis = list(title = TeX("\\psi_2"))) %>%
#          config(mathjax = 'cdn')
```


### Interpolating
```{r, echo=FALSE}
Noise_Type="Interpol"
covtype=3
prior=0
n=500
type_simul=1

appendy=paste0(Noise_Type,"_covtype",covtype,"_prior",prior,"_n",n,"_type_simul",type_simul,".csv")
pre="C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Code/ComputerExperiments/Simulation II/Interpolating"
theta=read.csv(paste0(pre,"/theta_",appendy))
xhist=read.csv(paste0(pre,"/xhist_",appendy))
yhist=read.csv(paste0(pre,"/yhist_",appendy))
Final_Data=read.csv(paste0(pre,"/Final_Data_",appendy))
coly=c("GP","IPW")


data_grid2=data.frame(theta1=Final_Data$x[Final_Data$groupy==1],
                      theta2=Final_Data$y[Final_Data$groupy==1],
                      value=Final_Data$z[Final_Data$groupy==1])
plot_matrix2 <- t(acast(data_grid2, theta1~ theta2, value.var="value"))

plot_ly(
  x = as.numeric(colnames(plot_matrix2)),
  y = as.numeric(rownames(plot_matrix2)),
  z = plot_matrix2) %>%
  add_surface()%>%
  layout(title="Value of Regime for Varying Cutoffs \n IPW",
         scene=list(xaxis = list(title="Psi_1"),
                    yaxis = list(title="Psi_2"),
                    zaxis =  list(title="Y")))


# fig=plot_ly(x=~Final_Data$x[Final_Data$groupy==1],
#             y=~Final_Data$y[Final_Data$groupy==1],
#             z=~Final_Data$z[Final_Data$groupy==1], type="contour",
#             colorscale="Greys",line=list(color="black"), contours = list(showlabels = TRUE))
# fig%>%colorbar(title = "Value")%>%
#   layout(xaxis = list(title = TeX("\\psi_1")),
#          yaxis = list(title = TeX("\\psi_2"))) %>%
#          config(mathjax = 'cdn') %>%
#   add_trace(x=~Final_Data$x[Final_Data$groupy==2],y=~Final_Data$y[Final_Data$groupy==2],
#             type = "scatter", mode="markers", marker=list(color="grey"),inherit=FALSE)
```


### Homoskedastic
```{r,echo=FALSE}
Noise_Type="Homosk"
type_simul=2
covtype=3
prior=0
n=500

appendy=paste0(Noise_Type,"_covtype",covtype,"_prior",prior,"_n",n,"_type_simul",type_simul,".csv")
pre="C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Code/ComputerExperiments/Simulation II/Homoskedastic"

theta=read.csv(paste0(pre,"/theta_",appendy))
xhist=read.csv(paste0(pre,"/xhist_",appendy))
yhist=read.csv(paste0(pre,"/yhist_",appendy))
Final_Data=read.csv(paste0(pre,"/Final_Data_",appendy))
coly=c("GP","IPW")


data_grid2=data.frame(theta1=Final_Data$x[Final_Data$groupy==1],
                      theta2=Final_Data$y[Final_Data$groupy==1],
                      value=Final_Data$z[Final_Data$groupy==1])
plot_matrix2 <- t(acast(data_grid2, theta1~ theta2, value.var="value"))

plot_ly(
  x = as.numeric(colnames(plot_matrix2)),
  y = as.numeric(rownames(plot_matrix2)),
  z = plot_matrix2) %>%
  add_surface()%>%
  layout(title="Value of Regime for Varying Cutoffs \n IPW",
         scene=list(xaxis = list(title="Psi_1"),
                    yaxis = list(title="Psi_2"),
                    zaxis =  list(title="Y")))
#--------------------------------------------------
# fig=plot_ly(x=~Final_Data$x[Final_Data$groupy==1],
#             y=~Final_Data$y[Final_Data$groupy==1],
#             z=~Final_Data$z[Final_Data$groupy==1], type="contour",
#             colorscale="Greys",line=list(color="black"), contours = list(showlabels = TRUE))
# fig%>%colorbar(title = "Value")%>%
#   layout(xaxis = list(title = TeX("\\psi_1")),
#          yaxis = list(title =TeX("\\psi_2"))) %>%
#          config(mathjax = 'cdn') %>%
#   add_trace(x=~Final_Data$x[Final_Data$groupy==2],y=~Final_Data$y[Final_Data$groupy==2],
#             type = "scatter", mode="markers", marker=list(color="grey"),inherit=FALSE)
```



### Heteroskedastic

```{r,echo=FALSE}
Noise_Type="Heterosk"
type_simul=3
covtype=3
prior=0
n=500

appendy=paste0(Noise_Type,"_covtype",covtype,"_prior",prior,"_n",n,"_type_simul",type_simul,".csv")
pre="C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Code/ComputerExperiments/Simulation II/Heteroskedastic"

theta=read.csv(paste0(pre,"/theta_",appendy))
xhist=read.csv(paste0(pre,"/xhist_",appendy))
yhist=read.csv(paste0(pre,"/yhist_",appendy))
Final_Data=read.csv(paste0(pre,"/Final_Data_",appendy))
coly=c("GP","IPW")


data_grid2=data.frame(theta1=Final_Data$x[Final_Data$groupy==1],
                      theta2=Final_Data$y[Final_Data$groupy==1],
                      value=Final_Data$z[Final_Data$groupy==1])
plot_matrix2 <- t(acast(data_grid2, theta1~ theta2, value.var="value"))

plot_ly(
  x = as.numeric(colnames(plot_matrix2)),
  y = as.numeric(rownames(plot_matrix2)),
  z = plot_matrix2) %>%
  add_surface()%>%
  layout(title="Value of Regime for Varying Cutoffs \n IPW",
         scene=list(xaxis = list(title="Psi_1"),
                    yaxis = list(title="Psi_2"),
                    zaxis =  list(title="Y")))

#--------------------------------------------------------
# fig=plot_ly(x=~Final_Data$x[Final_Data$groupy==1],
#             y=~Final_Data$y[Final_Data$groupy==1],
#             z=~Final_Data$z[Final_Data$groupy==1], type="contour",
#             colorscale="Greys",line=list(color="black"), contours = list(showlabels = TRUE))
# fig%>%colorbar(title = "Value")%>%
#   layout(xaxis = list(title = TeX("\\psi_1")),
#          yaxis = list(title =TeX("\\psi_2"))) %>%
#          config(mathjax = 'cdn') %>%
#   add_trace(x=~Final_Data$x[Final_Data$groupy==2],y=~Final_Data$y[Final_Data$groupy==2],
#             type = "scatter", mode="markers", marker=list(color="grey"),inherit=FALSE)

```

```{r,eval=FALSE,echo=FALSE}
  true_x=c(1.8,-0.3)
  true_value=0.2414571
#----- Reading in data
pathy="C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Code/ComputerExperiments/Simulation II/"
TabyVal_mean=read.csv(file=paste0(pathy,"SimulationII_TablesFigures/TabyVal_mean_n500.csv"),row.names=1)
Tabypsi1_mean=read.csv(file=paste0(pathy,"SimulationII_TablesFigures/Tabypsi1_mean_n500.csv"),row.names=1)
Tabypsi2_mean=read.csv(file=paste0(pathy,"SimulationII_TablesFigures/Tabypsi2_mean_n500.csv"),row.names=1)

TabyVal_median=read.csv(file=paste0(pathy,"SimulationII_TablesFigures/TabyVal_median_n500.csv"),row.names=1)
Tabypsi1_median=read.csv(file=paste0(pathy,"SimulationII_TablesFigures/Tabypsi1_median_n500.csv"),row.names=1)
Tabypsi2_median=read.csv(file=paste0(pathy,"SimulationII_TablesFigures/Tabypsi2_median_n500.csv"),row.names=1)


xtable(Tabypsi1_median,caption=paste0("psi1 Median (IQR). Known value:",true_x[1]))
xtable(Tabypsi2_median,caption=paste0("psi2 Median (IQR). Known value:",true_x[2]))
xtable(TabyVal_median,caption=paste0("Value Median (IQR). Known value:",true_value))

xtable(Tabypsi1_mean,caption=paste0("psi1 Mean (IQR). Known value:",true_x[1]))
xtable(Tabypsi2_mean,caption=paste0("psi2 Mean (IQR). Known value:",true_x[2]))
xtable(TabyVal_mean,caption=paste0("Value Mean (IQR). Known value:",true_value))

```



```{r,fig.width = 10, fig.height = 5,echo=FALSE,eval=FALSE}
  true_x=c(1.8,-0.3)
  true_value=0.2414571
  
  Valmat=read.csv(file="C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Code/ComputerExperiments/Simulation II/SimulationII_TablesFigures/Valmat_n500.csv")

  keep=seq(1,25,2)
  Valmat=Valmat[Valmat$Samp_numb %in% keep,]

p1=ggplot(Valmat, aes(y=psi1, x=Samp_numb, group=interaction(type_simul,Samp_numb), col=as.factor(type_simul))) +  
  geom_boxplot(width=1.4,outlier.size = 0.6)+geom_point(position=position_dodge(width=1.4),size=0.6)+theme_bw()+
  scale_color_manual(name  ="Type",labels=c("Interpolating", "Homoskedastic","Heteroskedastic"),values=c("gray4", "gray50","gray70"))+
  geom_hline(yintercept=true_x[1], linetype="dashed")+
  theme(text = element_text(size = 20))+
  labs(x ="Number of Additional Points", y = "Optimal Threshold")

jpeg("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Manuscript/SimulationII_Figures/boxplotpsi1_n500_covtype3_homonoise.jpg", width = 1000, height = 500)
p1
dev.off()

p2=ggplot(Valmat, aes(y=psi2, x=Samp_numb, group=interaction(type_simul,Samp_numb), col=as.factor(type_simul))) +  
  geom_boxplot(width=1.4,outlier.size = 0.5)+geom_point(position=position_dodge(width=1.4),size=0.5)+theme_bw()+
  scale_color_manual(name  ="Type",labels=c("Interpolating", "Homoskedastic","Heteroskedastic"),values=c("gray4", "gray50","gray70"))+
  geom_hline(yintercept=true_x[2], linetype="dashed")+
  theme(text = element_text(size = 20))+
  labs(x ="Number of Additional Points", y = "Optimal Threshold")
jpeg("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Manuscript/SimulationII_Figures/boxplotpsi2_n500_covtype3_homonoise.jpg", width = 1000, height = 500)
p2
dev.off()


p3=ggplot(Valmat, aes(y=Value, x=Samp_numb, group=interaction(type_simul,Samp_numb), col=as.factor(type_simul))) +  
  geom_boxplot(width=1.4,outlier.size = 0.5)+geom_point(position=position_dodge(width=1.4),size=0.5)+theme_bw()+
  scale_color_manual(name  ="Type",labels=c("Interpolating", "Homoskedastic","Heteroskedastic"),values=c("gray4", "gray50","gray70"))+
  geom_hline(yintercept=true_value, linetype="dashed")+
  theme(text = element_text(size = 20))+
  labs(x ="Number of Additional Points", y = "Value at Optimum")
jpeg("C:/Users/Administrator/Dropbox/Daniel_PhD_Research/Objective II/Manuscript/SimulationII_Figures/boxplotvalue_n500_covtype3_homonoise.jpg", width = 1000, height = 500)
p3
dev.off()
```







